### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by EduardoA-13** [PixelExperience-Devices/kernel_xiaomi_lavender#1]
I have this error when compiling

`drivers/bluetooth/btfm_slim.c:26:23: error fatal: btfm_slim.h: No existe el archivo o el directorio
 #include <btfm_slim.h>
                       ^
compilación terminada.
scripts/Makefile.build:282: recipe for target 'drivers/bluetooth/btfm_slim.o' failed
make[2]: *** [drivers/bluetooth/btfm_slim.o] Error 1
scripts/Makefile.build:489: recipe for target 'drivers/bluetooth' failed
make[1]: *** [drivers/bluetooth] Error 2
Makefile:1024: recipe for target 'drivers' failed
make: *** [drivers] Error 2
`

**Comment by faham1997** [comment]
Probably problem from your side.
